name: Create homework repositories

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!main'
  workflow_dispatch:
  schedule: 
    - cron: '0 0 * * *'

permissions: write-all

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  homework_creation:
    name: Create homework repository
    runs-on: ubuntu-latest
    env:
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: npm ci
      - run: node ./scripts/index.js
